### PR TITLE
brochure

### PR DESCRIPTION
**Pull request by jeesupark96**
image

### CODE REVIEW

**Review by TimelikeClosure — CHANGES_REQUESTED** [review]
- Please adjust the input, label and button sizes/locations to more closely match the reference image.
- Please adjust the select background color to something closer to the reference color.
- The submit button has a typo.

---

image

---

image

**Comment by jeesupark96** [comment]
image

**Comment by jeesupark96** [comment]
sorry I have to change the background right now!

**Comment by jeesupark96** [comment]
image

**Review by TimelikeClosure — APPROVED** [review]
Looks significantly closer to the reference image. If you'd like to spend a little time tweaking the spacing in the inputs and around the labels to bring it closer, you're welcome to, but this is good enough to pass the challenge.

**Pull request merged**
