### PR TITLE
canvas medical

### PR DESCRIPTION
**Pull request by jeesupark96**
image

### CODE REVIEW

**Review by Zhiwutian — CHANGES_REQUESTED** [review]
Hey Jeesu, the first thing to address is that there is a large amount of position absolute being used in this solution, and that is something to avoid, especially mixing it with display flex. I would recommend rebuilding the layout using flex with proper column classes and avoiding position absolute except for the main image at the top of the page. Reach out if you have questions on setting up the flex layout!

**Comment by jeesupark96** [comment]
Yeah I definitely realized that too
would you recommend me just starting over?

**Comment by jeesupark96** [comment]
https://user-images.githubusercontent.com/90468158/144998271-9bd348bd-744c-47d8-89a8-e7cf2d4be358.mp4

**Review by Zhiwutian — CHANGES_REQUESTED** [review]
looking good! so there are just a couple adjustments to make:
1. the main image should be lower to match the distance of the example from the header
2.  the columns in `clinicians prefer canvas` section need to be adjusted so that the spacing of the text more closely matches the example.
Almost there!

**Review by Zhiwutian — APPROVED** [review]
👍🏼

**Pull request merged**
